// Package webhook receives provider callbacks, deduplicates them, and applies
// them to payment transactions.
//
// Three properties drive the whole design, and each of them is a thing that
// happens routinely in production rather than a theoretical edge case:
//
//  1. The same event arrives more than once, because providers retry deliveries
//     they believe failed.
//  2. Events arrive out of order, because delivery is concurrent and retries
//     overtake first attempts.
//  3. An event can arrive *before* the API response that created the state it
//     describes, because the provider's callback and its HTTP reply race.
//
// Ingestion is therefore deliberately fast and dumb — verify, persist, ack —
// and everything interesting happens afterwards, asynchronously, guarded. A
// provider that gets a slow 200 retries and amplifies load at exactly the moment
// the receiver is already struggling.
package webhook

import (
	"errors"
	"time"

	"github.com/lequoctrung/payment-orchestrator/internal/psp"
)

var (
	// ErrUnknownProvider means no verifier is registered for the route.
	ErrUnknownProvider = errors.New("unknown webhook provider")

	// ErrInvalidSignature covers both a wrong signature and a missing one.
	// They are one error on purpose: distinguishing them tells an attacker
	// which half of the scheme they got right.
	ErrInvalidSignature = errors.New("webhook signature is invalid")

	// ErrTimestampOutsideWindow means the request is outside the replay window.
	// A valid signature is not enough — without a bounded window, one captured
	// request stays replayable forever.
	ErrTimestampOutsideWindow = errors.New("webhook timestamp is outside the accepted window")

	ErrMalformedPayload = errors.New("webhook payload is malformed")
)

// Event is a provider callback in this system's vocabulary.
//
// Provider payload shapes differ in every particular; this is what the receiver
// actually needs, and mapping into it is the per-provider adapter's job.
type Event struct {
	// ProviderEventID is the provider's identifier for the delivery. It is the
	// deduplication key, so an adapter that cannot supply one must fail rather
	// than invent one — a generated id would make every redelivery look new.
	ProviderEventID string

	// Reference is the provider's charge reference, and the only identifier a
	// webhook carries that can find a transaction.
	Reference string

	// Sequence is the provider's ordering token, normalised.
	//
	// A sequence rather than a timestamp because timestamps are generated by
	// whichever provider host emitted the event, and two hosts a few
	// milliseconds apart routinely disagree about which of two events came
	// first.
	//
	// Whatever the adapter puts here is authoritative, including zero. Nothing
	// downstream may treat a low value as "missing" and substitute something
	// larger: that turns the oldest event in a batch into the newest, which is
	// precisely the mistake the staleness guard exists to catch. An adapter for
	// a provider that exposes no ordering token derives one from OccurredAt
	// itself, because only the adapter knows that is what it is doing.
	Sequence int64

	OccurredAt time.Time

	Status    psp.Status
	RawStatus string
}

// Headers reads a request header. A function rather than a map so the HTTP
// layer's own representation does not leak into this package.
type Headers func(key string) string

// Verifier authenticates and parses one provider's callbacks.
//
// Deliberately per provider, with no shared "generic HMAC" implementation.
// Signature schemes differ in what they sign, how they encode it, and which
// headers carry it; a shared verifier accumulates conditionals until nobody can
// say what any single provider actually requires.
type Verifier interface {
	Name() string

	// Verify authenticates the exact bytes received. Implementations must use a
	// constant-time comparison: a byte-by-byte compare leaks, through timing,
	// how much of a forged signature was correct, which is enough to construct
	// a valid one.
	Verify(hdr Headers, body []byte, now time.Time) error

	// Parse maps the payload into an Event. Called only after Verify succeeds.
	Parse(body []byte) (*Event, error)

	// SignatureHeader names the header carrying the signature, so the raw log
	// can keep it alongside the bytes it authenticates.
	SignatureHeader() string
}

// Registry resolves a provider name to its verifier.
type Registry struct {
	verifiers map[string]Verifier
}

func NewRegistry(verifiers ...Verifier) *Registry {
	r := &Registry{verifiers: make(map[string]Verifier, len(verifiers))}
	for _, v := range verifiers {
		r.verifiers[v.Name()] = v
	}
	return r
}

func (r *Registry) Get(name string) (Verifier, error) {
	v, ok := r.verifiers[name]
	if !ok {
		return nil, ErrUnknownProvider
	}
	return v, nil
}
